package com.pse.tixclick.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

@Getter
public enum ErrorCode {
    UNCATEGORIZED_EXCEPTION(9999, "Uncategorized error", HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_KEY(1001, "Invalid key", HttpStatus.BAD_REQUEST),
    USER_EXISTED(1002, "Tài khoản đã tồn tại", HttpStatus.BAD_REQUEST),
    USERNAME_INVALID(1003, "Username must be at least {min} characters", HttpStatus.BAD_REQUEST),
    INVALID_PASSWORD(1004, "Password must be at least {min} characters", HttpStatus.BAD_REQUEST),
    USER_NOT_EXISTED(1005, "Tài khoản không tồn tại", HttpStatus.NOT_FOUND),
    UNAUTHENTICATED(1006, "Mật khẩu không hợp lệ", HttpStatus.UNAUTHORIZED),
    UNAUTHORIZED(1007, "bạn không có quyền", HttpStatus.FORBIDDEN),
    INVALID_DOB(1008, "Your age must be at least {min}", HttpStatus.BAD_REQUEST),
    PASSWORD_NOT_CORRECT(1009, "Sai mật khẩu", HttpStatus.UNAUTHORIZED),
    EMAIL_TAKEN(1010, "Email đã tồn tại", HttpStatus.BAD_REQUEST),
    EMPTY_FIELD(1011, "You cannot leave required field(s) empty", HttpStatus.BAD_REQUEST),
    ITEM_NOT_FOUND(1012, "Item not found", HttpStatus.NOT_FOUND),
    PHONE_TAKEN(1013, "Phone number already in use", HttpStatus.BAD_REQUEST),
    INVALID_TOKEN(1014, "Token không hợp lệ", HttpStatus.BAD_REQUEST),
    EMAIL_NOT_EXISTED(1015, "Email not existed", HttpStatus.NOT_FOUND),
    ID_EXISTED(1016, "Id already exists", HttpStatus.BAD_REQUEST),
    ID_NOT_MATCHED(1017, "Id does not match request", HttpStatus.BAD_REQUEST),
    POST_CATEGORY_NOT_FOUND(1018, "Post category not found", HttpStatus.NOT_FOUND),
    INVALID_REFRESH_TOKEN(1019, "Invalid refresh token", HttpStatus.BAD_REQUEST),
    INVALID_EMAIL(1020, "Invalid email", HttpStatus.BAD_REQUEST),
    INVALID_EMAIL_FORMAT(1021, "Invalid email format", HttpStatus.BAD_REQUEST),
    ROLE_NOT_EXISTED(1022, "role không đúng", HttpStatus.NOT_FOUND),
    USER_ACTIVE(1023, "User is active", HttpStatus.BAD_REQUEST),
    GITHUB_ERROR(1024, "Lỗi Đăng nhập Github", HttpStatus.BAD_REQUEST),
    FACEBOOK_LOGIN_FAILED(1025, "Lỗi Đăng nhập Google", HttpStatus.BAD_REQUEST),
    INVALID_EVENT_DATA(1026, "Tạo event bị lỗi", HttpStatus.BAD_REQUEST),
    DATABASE_ERROR(1027, "Lỗi kết nối cơ sở dữ liệu", HttpStatus.INTERNAL_SERVER_ERROR),
    CATEGORY_NOT_FOUND(1028, "Không tìm thấy danh mục", HttpStatus.NOT_FOUND),
    INVALID_EVENT_TYPE(1029, "Loại sự kiện không hợp lệ", HttpStatus.BAD_REQUEST),
    EVENT_NOT_FOUND(1030, "Không tìm thấy sự kiện", HttpStatus.NOT_FOUND),
    IMAGE_NOT_FOUND(1031, "Không tìm thấy ảnh", HttpStatus.NOT_FOUND),
    IMAGE_REMOVE_FAILED(1032, "Xóa ảnh thất bại", HttpStatus.BAD_REQUEST),
    ACTIVITY_NOT_FOUND(1033, "Không tìm thấy hoạt động", HttpStatus.NOT_FOUND),
    TICKET_NOT_FOUND(1034, "Không tìm thấy vé", HttpStatus.NOT_FOUND),
    COMPANY_NOT_FOUND(1035, "Không tìm thấy công ty", HttpStatus.NOT_FOUND),
    CANNOT_CREATE_MEMBER(1036, "Không thể tạo thành viên", HttpStatus.BAD_REQUEST),
    INVALID_ROLE(1037, "Vai trò không hợp lệ", HttpStatus.BAD_REQUEST),
    MEMBER_NOT_FOUND(1038, "Không tìm thấy thành viên", HttpStatus.NOT_FOUND),
    COMPANY_INACTIVE(1039, "Công ty chưa được hoạt động", HttpStatus.BAD_REQUEST),
    ROLE_NOT_FOUND(1040, "Không tìm thấy vai trò", HttpStatus.NOT_FOUND),
    BACKGROUND_NOT_FOUND(1041, "Không tìm thấy background", HttpStatus.NOT_FOUND),
    SEATMAP_NOT_FOUND(1042, "Không tìm thấy seatmap", HttpStatus.NOT_FOUND),
    COMPANY_NOT_EXISTED(1043, "Công ty không tồn tại", HttpStatus.NOT_FOUND),
    FILE_UPLOAD_FAILED(1044, "Tải lên tệp thất bại", HttpStatus.BAD_REQUEST),
    FILE_TOO_LARGE(1045, "File không vượt quá 10mb", HttpStatus.BAD_REQUEST),
    INVALID_FILE_TYPE(1046, "Loại tệp không hợp lệ", HttpStatus.BAD_REQUEST),
    COMPANY_VERIFICATION_NOT_FOUND(1047, "Không tìm thấy xác minh công ty", HttpStatus.NOT_FOUND),
    NOT_OWNER(1048, "Bạn không phải chủ sở hữu", HttpStatus.FORBIDDEN),
    COMPANY_NOT_ACTIVE(1049, "Công ty chưa được kích hoạt", HttpStatus.BAD_REQUEST),
    INVALID_COMPANY(1050, "Công ty không hợp lệ", HttpStatus.BAD_REQUEST),
    NOT_PERMISSION(1051, "Bạn không có quyền", HttpStatus.FORBIDDEN),
    EVENT_ACTIVITY_NOT_FOUND(1052, "Không tìm thấy hoạt động sự kiện", HttpStatus.NOT_FOUND),
    STATUS_NOT_CORRECT(1053, "Tình trạng event không đúng", HttpStatus.BAD_REQUEST),
    ZONE_NOT_FOUND(1054, "Không tìm thấy zone", HttpStatus.NOT_FOUND),
    SEAT_NOT_FOUND(1055, "Không tìm thấy seat", HttpStatus.NOT_FOUND),
    TICKET_PURCHASE_NOT_FOUND(1056, "Không tìm thấy ticket purchase", HttpStatus.NOT_FOUND),
    INVALID_QUANTITY(1057, "Số lượng không hợp lệ", HttpStatus.BAD_REQUEST),
    VOUCHER_NOT_FOUND(1058, "Không tìm thấy voucher", HttpStatus.NOT_FOUND),
    ORDER_NOT_FOUND(1059, "Không tìm thấy order", HttpStatus.NOT_FOUND),
    ACCOUNT_NOT_FOUND(1060, "Không tìm thấy account", HttpStatus.NOT_FOUND),
    ZONE_TYPE_NOT_FOUND(1061, "Không tìm thấy zone type", HttpStatus.NOT_FOUND),
    CONTRACT_NOT_FOUND(1062, "Không tìm thấy contract", HttpStatus.NOT_FOUND),
    SEAT_NOT_AVAILABLE(1062, "Ghế không khả dụng", HttpStatus.BAD_REQUEST),
    DUPLICATE_TICKET_PURCHASE(1063, "Ticket purchase đã tồn tại", HttpStatus.BAD_REQUEST),
    ZONE_FULL(1064, "Zone đã đầy", HttpStatus.BAD_REQUEST),
    TICKET_PURCHASE_EXPIRED(1065, "Ticket purchase đã hết hạn", HttpStatus.BAD_REQUEST),
    COMPANY_USERNAME_EXISTED(1066, "Tên công ty đã tồn tại", HttpStatus.BAD_REQUEST),
    CONTRACT_DOCUMENT_NOT_FOUND(1067, "Không tìm thấy contract document", HttpStatus.NOT_FOUND),
    FILE_NOT_FOUND(1068, "Không tìm thấy file", HttpStatus.NOT_FOUND),
    COMPANY_VERIFICATION_NOT_REJECTED(1069, "Xác minh công ty không bị từ chối", HttpStatus.BAD_REQUEST),
    USER_NOT_MANAGER(1070, "Người dùng không phải là quản lý", HttpStatus.BAD_REQUEST),
    ACCOUNT_NOT_CREATE_COMPANY(1071, "Tài khoản không phải đại diện công ty", HttpStatus.BAD_REQUEST),
    OTP_ALREADY_SENT(1072, "OTP đã được gửi", HttpStatus.BAD_REQUEST),
    USER_NOT_ACTIVE(1073, "Tài khoản chưa được kích hoạt", HttpStatus.BAD_REQUEST),
    TICKET_PURCHASE_CHECKED_IN(1074, "Ticket purchase đã được check in", HttpStatus.BAD_REQUEST),
    CHECKIN_LOG_NOT_FOUND(1075, "Không tìm thấy checkin log", HttpStatus.NOT_FOUND),
    CHECKIN_LOG_EXPIRED(1076, "Checkin log đã hết hạn", HttpStatus.BAD_REQUEST),
    CHECKIN_LOG_CHECKED_IN(1077, "Checkin log đã được check in", HttpStatus.BAD_REQUEST),
    UNAUTHENTICATED_LOGIN(1078, "bạn không đủ quyền truy cập", HttpStatus.UNAUTHORIZED),
    NOTIFICATION_NOT_EXISTED(1079, "Notification không tồn tại", HttpStatus.NOT_FOUND),
    TICKET_MAPPING_NOT_FOUND(1080, "Không tìm thấy ticket mapping", HttpStatus.NOT_FOUND),
    TICKET_MAPPING_EMPTY(1081, "Ticket mapping đã hết", HttpStatus.BAD_REQUEST),
    CONTRACT_PAYMENT_NOT_FOUND(1082, "Không tìm thấy contract payment", HttpStatus.NOT_FOUND),
    CONTRACT_DETAIL_NOT_FOUND(1083, "Không tìm thấy contract detail", HttpStatus.NOT_FOUND),
    CONTRACT_DETAIL_CODE_NOT_FOUND(1084, "Không tìm thấy contract detail code", HttpStatus.NOT_FOUND),
    CONTRACT_NAME_NOT_FOUND(1085, "Không tìm thấy contract name", HttpStatus.NOT_FOUND),
    BANKING_NAME_NOT_FOUND(1086, "Không tìm thấy banking name", HttpStatus.NOT_FOUND),
    BANKING_CODE_NOT_FOUND(1087, "Không tìm thấy banking code", HttpStatus.NOT_FOUND),
    QR_CODE_NOT_FOUND(1084, "Không tìm thấy qr code", HttpStatus.NOT_FOUND),
    ACTIVITY_EXISTED(1085, "Hoạt động đã tồn tại", HttpStatus.BAD_REQUEST),
    NOT_MANAGER_IN_DATABASE(1086, "Không tìm thấy quản lý trong cơ sở dữ liệu", HttpStatus.NOT_FOUND),
    TICKET_MAPPING_NOT_ENOUGH(1085, "Số lượng vé còn lai không đủ", HttpStatus.BAD_REQUEST),
    ZONE_NOT_ENOUGH(1086, "Zone không đủ", HttpStatus.BAD_REQUEST),
    ACTIVITY_ASSIGNMENT_NOT_FOUND(1087, "Không tìm thấy activity assignment", HttpStatus.NOT_FOUND),
    ZONE_ACTIVITY_NOT_FOUND(1088, "Không tìm thấy zone activity", HttpStatus.NOT_FOUND),
    SEAT_ACTIVITY_NOT_FOUND(1089, "Không tìm thấy seat activity", HttpStatus.NOT_FOUND),
    SEAT_SOLD_OUT(1090, "Ghế đã bán", HttpStatus.BAD_REQUEST),
    INVALID_PIN_CODE(1091, "Mã PIN không hợp lệ", HttpStatus.BAD_REQUEST),
    MANAGER_NOT_FOUND(1092, "Không tìm thấy manager phù hợp", HttpStatus.NOT_FOUND),
    TICKET_EXISTED(1093, "Vé đã tồn tại", HttpStatus.BAD_REQUEST),
    CONTRACT_VERIFICATION_NOT_FOUND(1094, "Không tìm thấy contract verification", HttpStatus.NOT_FOUND),
    CONTRACT_VERIFICATION_NOT_PENDING(1095, "Contract verification không ở trạng thái pending", HttpStatus.BAD_REQUEST),
    SEAT_MAP_NOT_FOUND(1096, "Không tìm thấy seat map", HttpStatus.NOT_FOUND),
    NEEDED_LOGIN(1097, "Bạn cần đăng nhập", HttpStatus.UNAUTHORIZED),
    CONTRACT_ALREADY_EXISTS(1098, "Contract đã tồn tại", HttpStatus.BAD_REQUEST),
    INVALID_EVENT_STATUS(1099, "Tình trạng sự kiện không hợp lệ", HttpStatus.BAD_REQUEST),
    TICKET_PURCHASE_CANCELLED(1098, "Ticket purchase đã bị hủy", HttpStatus.BAD_REQUEST),
    ORDER_PENDING(1099, "Order đang chờ xử lý", HttpStatus.BAD_REQUEST),
    EVENT_NOT_HAVE_SEATMAP(1100, "Sự kiện không có seatmap", HttpStatus.BAD_REQUEST),
    EVENT_ONLINE(1101, "Sự kiện online không có seatmap", HttpStatus.BAD_REQUEST),
    ACCOUNT_ALREADY_EXISTS(1102, "Tài khoản đã tồn tại", HttpStatus.BAD_REQUEST),
    MEMBER_ACTIVITY_NOT_FOUND(1103, "Không tìm thấy hoạt động thành viên", HttpStatus.NOT_FOUND),
    MEMBER_ACTIVITY_ALREADY_EXISTS(1104, "Hoạt động thành viên đã tồn tại", HttpStatus.BAD_REQUEST),
    INTERNAL_SERVER_ERROR(1105, "Internal server error", HttpStatus.INTERNAL_SERVER_ERROR),
    CAN_NOT_UPDATE_OWNER(1106, "Không thể cập nhật owner", HttpStatus.BAD_REQUEST),
    MEMBER_INACTIVE(1107, "Thành viên không hoạt động", HttpStatus.BAD_REQUEST),
    CANNOT_UPDATE(1108, "Không thể cập nhật thành viên", HttpStatus.BAD_REQUEST),
    EVENT_TYPE_NOT_ONLINE(1109, "Sự kiện không phải là sự kiện online", HttpStatus.BAD_REQUEST),
    NOT_PERMISSION_ORGANIZER(1110, "Bạn không có quyền mua vé sự kiện này", HttpStatus.FORBIDDEN),
    INVALID_OTP(1111, "Mã OTP không hợp lệ", HttpStatus.BAD_REQUEST),
    USERNAME_TAKEN(1112, "Tên tài khoản đã tồn tại", HttpStatus.BAD_REQUEST),
    OTP_ALREADY_SENT_RECENTLY(1113, "Mã OTP đã được gửi gần đây", HttpStatus.BAD_REQUEST),
    EVENT_ALREADY_APPROVED(1114, "Sự kiện đã được phê duyệt", HttpStatus.BAD_REQUEST),
    COMPANY_VERIFICATION_PENDING(1115, "Xác minh công ty đang chờ xử lý", HttpStatus.BAD_REQUEST),
    EVENT_NOT_PENDING_APPROVAL(1116, "Sự kiện không đang chờ phê duyệt", HttpStatus.BAD_REQUEST),
    EVENT_NOT_APPROVED(1117, "Sự kiện chưa được phê duyệt", HttpStatus.BAD_REQUEST),
    EVENT_SCHEDULED(1118, "Sự kiện đã được lên lịch", HttpStatus.BAD_REQUEST),
    CONTRACT_EXISTED(1119, "Hợp đồng đã tồn tại", HttpStatus.BAD_REQUEST),
    TRANSACTION_NOT_FOUND(1120, "Không tìm thấy giao dịch", HttpStatus.NOT_FOUND),
    CONTRACT_SCANNING_FAILED(1121, "Quét hợp đồng thất bại", HttpStatus.BAD_REQUEST),
    MEMBER_NOT_EXISTED(1122, "Thành viên không tồn tại", HttpStatus.NOT_FOUND),
    EVENT_NOT_COMPANY(1123, "Sự kiện không thuộc công ty", HttpStatus.BAD_REQUEST),
    TRANSACTION_EXISTED(1124, "Giao dịch đã tồn tại", HttpStatus.BAD_REQUEST),
    VOUCHER_CODE_ALREADY_EXISTS(1125, "Voucher code đã tồn tại", HttpStatus.BAD_REQUEST),
    ACCOUNT_NOT_HAVE_COMPANY(1126, "Tài khoản không có công ty", HttpStatus.BAD_REQUEST),
    CAN_NOT_UPDATE(1127, "Không thể cập nhật", HttpStatus.BAD_REQUEST),
    MEMBER_TIME_CONFLICT(1128, "Thành viên đã có hoạt động trùng thời gian", HttpStatus.BAD_REQUEST),
    MEMBER_ALREADY_ASSIGNED(1129, "Thành viên đã được phân công", HttpStatus.BAD_REQUEST),
    EVENT_NOT_EXISTED(1130, "Sự kiện không tồn tại", HttpStatus.NOT_FOUND),
    COMPANY_VERIFICATION_NOT_EXISTED(1131, "Xác minh công ty không tồn tại", HttpStatus.NOT_FOUND),
    COMPANY_NOT_REJECTED(1132, "Công ty không bị từ chối", HttpStatus.BAD_REQUEST),
    TICKET_NOT_MY_ACCOUNT(1133, "Vé không thuộc tài khoản của bạn", HttpStatus.BAD_REQUEST),
    SOLD_OUT_TICKET(1134, "Vé đã bán hết", HttpStatus.BAD_REQUEST),
    TICKET_PURCHASE_DONT_BUY(1135, "Ticket purchase chua mua", HttpStatus.BAD_REQUEST),
    TICKET_NOT_ENOUGH(1136, "Số lượng vé không đủ", HttpStatus.BAD_REQUEST),
    TICKET_REQUEST_EXCEED_QUANTITY(1137, "Số lượng vé yêu cầu vượt quá số lượng có sẵn", HttpStatus.BAD_REQUEST),
    SEAT_ALREADY_BOOKED(1138, "Ghế đã được đặt", HttpStatus.BAD_REQUEST),
    EVENT_NOT_SCHEDULED(1139, "Sự kiện không được lên lịch", HttpStatus.BAD_REQUEST),
    FORBIDDEN(1140, "Bạn không có quyền truy cập tài nguyên này", HttpStatus.FORBIDDEN),
    NOT_FOUNT_ROLE(1141, "Không tìm thấy vai trò", HttpStatus.NOT_FOUND),
    NO_CHANGE_TICKET_SAME(1142,"Không thể đổi vé cùng loai được",HttpStatus.BAD_REQUEST),
    NO_CHANGE_ZONE_TICKET(1143,"Không thể đổi vé đứng cùng loại được", HttpStatus.BAD_REQUEST),
    ORDER_DETAIL_NOT_FOUND(1144,"Không tìm thấy order detail",HttpStatus.NOT_FOUND),
    VOUCHER_INACTIVE(1145,"Voucher hết hạn hoặc không hoạt động",HttpStatus.BAD_REQUEST),
    PAYMENT_NOT_FOUND(1146,"Không tìm thấy payment",HttpStatus.NOT_FOUND),
    INVALID_EVENT_DATE(1147,"Ngày sự kiện mới phải sau ngày sự kiện cũ",HttpStatus.BAD_REQUEST),
    TRANSACTION_ALREADY_EXISTS(1148,"Giao dịch đã tồn tại",HttpStatus.BAD_REQUEST),
    INVALID_PAGE_SIZE(1149,"Kích thước trang không hợp lệ",HttpStatus.BAD_REQUEST),
    PAYMENT_ALREADY_COMPLETED(1150,"Thanh toán đã hoàn tất",HttpStatus.BAD_REQUEST),
    INVALID_TICKET_CHANGE_CASE(1151,"Trường hợp đổi vé không hợp lệ",HttpStatus.BAD_REQUEST),
    INVALID_TICKET_CHANGE_REQUEST(1152,"Yêu cầu đổi vé không hợp lệ",HttpStatus.BAD_REQUEST),
    TICKET_SALE_NOT_STARTED(1153,"Bán vé chưa bắt đầu",HttpStatus.BAD_REQUEST),
    INVALID_QR_CODE(1154,"Mã QR không hợp lệ",HttpStatus.BAD_REQUEST),
    USER_NOT_BUYER(1155,"Người dùng không phải là người mua",HttpStatus.BAD_REQUEST),
    ORDER_CANCELLED(1156,"Đơn hàng đã bị hủy",HttpStatus.BAD_REQUEST),
    INVALID_REQUEST(1157,"Yêu cầu không hợp lệ",HttpStatus.BAD_REQUEST),
    EVENT_ACTIVITY_EXPIRED(1158,"Hoạt động sự kiện đã hết hạn",HttpStatus.BAD_REQUEST),
    EVENT_ACTIVITY_NOT_STARTED_YET(1159,"Hoạt động sự kiện chưa bắt đầu",HttpStatus.BAD_REQUEST),
    CANCEL_INSTALLMENT_CONTRACT(1160,"Không thể huỷ sự kiện có hợp đồng thanh toán nhiều lần",HttpStatus.BAD_REQUEST),
    EVENT_CONTRACT_EXISTED(1161,"Sự kiện này đã lên hợp đồng",HttpStatus.BAD_REQUEST),
    JUST_ONE_UPDATE(1162,"Chỉ được phép cập nhật một lần",HttpStatus.BAD_REQUEST),
    EVENT_CANCELLED(1163,"Sự kiện chưa bị hủy",HttpStatus.BAD_REQUEST),
    TICKET_NOT_REFUNDING(1164,"Vé không phải status hoàn tiền",HttpStatus.BAD_REQUEST),
    INVALID_SORT_DIRECTION(1165, "Hướng sắp xếp không hợp lệ", HttpStatus.BAD_REQUEST),
    CANNOT_CANCEL_EVENT_WITHIN_7_DAYS(1165,"Không thể hủy sự kiện trong vòng 7 ngày trước ngày diễn ra sự kiện",HttpStatus.BAD_REQUEST),
    PAYMENT1_NOT_FOUND(1146,"Không tìm thấy đơn hàng nào",HttpStatus.OK),
    TRANSACTION1_NOT_FOUND(1120, "Không tìm thấy giao dịch", HttpStatus.OK),
    EVENT1_NOT_FOUND(1030, "Không tìm thấy sự kiện", HttpStatus.OK),
    EVENT1_CANCELLED(1163,"Sự kiện chưa bị hủy",HttpStatus.OK),
    ACCOUNT1_NOT_FOUND(1060, "Không tìm thấy account", HttpStatus.OK),
    ORDER_ALREADY_SUCCESSFUL(1166, "Đơn hàng đã thành công", HttpStatus.BAD_REQUEST)


    ;





    ErrorCode(int code, String message, HttpStatusCode statusCode) {
        this.code = code;
        this.message = message;
        this.statusCode = statusCode;
    }

    private final int code;
    private final String message;
    private final HttpStatusCode statusCode;
}
